# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb1fd6cd593e26b34ddf7c7cc2348d9191698404854f326324439b40a89e03d761d2f98bf8b629bbc2ed7e5a8b53b250ea6c1d84d346923980bfadd0630d131e

test:
  secret_key_base: 173166148a683421d566598378fadfb1d96a9ce191d4124ee3b310afdcf5f938a4fd797ff7e9ff3b63b50871f233560d8cbe13e014d19b9f662f0a4f548fec5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
